version: '3.8'

services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa-dev
    restart: always
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
    networks:
      - dvwa-net
    volumes:
      - dvwa-html:/var/www/html
      - dvwa-mysql:/var/lib/mysql
      - ./custom_php.ini:/etc/php/7.0/apache2/conf.d/custom_php.ini

  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:latest
    container_name: devcontainer-vscode
    depends_on:
      - dvwa
    volumes:
      - ..:/workspace:cached
    networks:
      - dvwa-net
    command: sleep infinity

networks:
  dvwa-net:
    driver: bridge

volumes:
  dvwa-html:
  dvwa-mysql:
